# FEATURE SCALING

In [12]:
#Importing the libraries 
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
import warnings
warnings.filterwarnings('ignore')
from sklearn import preprocessing

In [13]:
#Importing data into Python
import os
os.getcwd()

'C:\\Users\\KALPANA  PATNALA\\Desktop\\Liver-Patients-Analysis\\Datasets'

In [14]:
os.chdir(r"C:\Users\KALPANA  PATNALA\Desktop\Liver-Patients-Analysis\Datasets")
os.getcwd()

'C:\\Users\\KALPANA  PATNALA\\Desktop\\Liver-Patients-Analysis\\Datasets'

In [15]:
data=pd.read_csv(r'C:\Users\KALPANA  PATNALA\Desktop\Liver-Patients-Analysis\Datasets\indian_liver_patient.csv')

In [16]:
data

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0     65  Female              0.7               0.1                   187   
1     62    Male             10.9               5.5                   699   
2     62    Male              7.3               4.1                   490   
3     58    Male              1.0               0.4                   182   
4     72    Male              3.9               2.0                   195   
..   ...     ...              ...               ...                   ...   
578   60    Male              0.5               0.1                   500   
579   40    Male              0.6               0.1                    98   
580   52    Male              0.8               0.2                   245   
581   31    Male              1.3               0.5                   184   
582   38    Male              1.0               0.3                   216   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                          16                          18             6.8   
1                          64                         100             7.5   
2                          60                          68             7.0   
3                          14                          20             6.8   
4                          27                          59             7.3   
..                        ...                         ...             ...   
578                        20                          34             5.9   
579                        35                          31             6.0   
580                        48                          49             6.4   
581                        29                          32             6.8   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  Dataset  
0        3.3                        0.90        1  
1        3.2                        0.74        1  
2        3.3                        0.89        1  
3        3.4                        1.00        1  
4        2.4                        0.40        1  
..       ...                         ...      ...  
578      1.6                        0.37        2  
579      3.2                        1.10        1  
580      3.2                        1.00        1  
581      3.4                        1.00        1  
582      4.4                        1.50        2  

[583 rows x 11 columns]

In [17]:
data.isnull().sum()

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    4
Dataset                       0
dtype: int64

In [18]:
data['Albumin_and_Globulin_Ratio'].mean()

0.9470639032815201

In [19]:
data.fillna(data.mean(),inplace=True)

In [20]:
data.isnull().sum()

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    0
Dataset                       0
dtype: int64

In [21]:
data['Albumin_and_Globulin_Ratio'].values

array([0.9      , 0.74     , 0.89     , 1.       , 0.4      , 1.3      ,
       1.       , 1.1      , 1.2      , 1.       , 0.8      , 0.6      ,
       0.9      , 1.       , 0.87     , 0.7      , 1.3      , 0.92     ,
       0.8      , 0.8      , 0.55     , 0.5      , 0.9      , 0.6      ,
       1.85     , 1.1      , 1.1      , 1.2      , 0.95     , 1.1      ,
       0.4      , 1.4      , 1.2      , 0.8      , 0.8      , 0.9      ,
       1.18     , 0.8      , 0.61     , 1.1      , 1.       , 1.1      ,
       0.6      , 1.       , 1.       , 0.9      , 1.34     , 1.3      ,
       1.       , 0.4      , 0.7      , 1.       , 1.3      , 1.2      ,
       0.5      , 0.5      , 1.       , 0.9      , 0.6      , 1.39     ,
       1.       , 1.       , 1.       , 0.7      , 0.6      , 0.8      ,
       1.6      , 1.4      , 1.4      , 0.9      , 1.2      , 0.6      ,
       0.8      , 1.2      , 1.       , 0.9      , 0.7      , 0.8      ,
       1.58     , 0.5      , 0.6      , 1.3      , 

In [27]:
data['Gender'].replace(['Male','Female'],[1,0],inplace=True)
data

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0     65       0              0.7               0.1                   187   
1     62       1             10.9               5.5                   699   
2     62       1              7.3               4.1                   490   
3     58       1              1.0               0.4                   182   
4     72       1              3.9               2.0                   195   
..   ...     ...              ...               ...                   ...   
578   60       1              0.5               0.1                   500   
579   40       1              0.6               0.1                    98   
580   52       1              0.8               0.2                   245   
581   31       1              1.3               0.5                   184   
582   38       1              1.0               0.3                   216   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                          16                          18             6.8   
1                          64                         100             7.5   
2                          60                          68             7.0   
3                          14                          20             6.8   
4                          27                          59             7.3   
..                        ...                         ...             ...   
578                        20                          34             5.9   
579                        35                          31             6.0   
580                        48                          49             6.4   
581                        29                          32             6.8   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  Dataset  
0        3.3                        0.90        1  
1        3.2                        0.74        1  
2        3.3                        0.89        1  
3        3.4                        1.00        1  
4        2.4                        0.40        1  
..       ...                         ...      ...  
578      1.6                        0.37        2  
579      3.2                        1.10        1  
580      3.2                        1.00        1  
581      3.4                        1.00        1  
582      4.4                        1.50        2  

[583 rows x 11 columns]

#Feature Egineering:
#Feature Egineering concentrate on sepereating input to features And output to label

In [28]:
#Seperating input columns(Independent) from the dataset
x=data.iloc[:,0:10]

In [29]:
x

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0     65       0              0.7               0.1                   187   
1     62       1             10.9               5.5                   699   
2     62       1              7.3               4.1                   490   
3     58       1              1.0               0.4                   182   
4     72       1              3.9               2.0                   195   
..   ...     ...              ...               ...                   ...   
578   60       1              0.5               0.1                   500   
579   40       1              0.6               0.1                    98   
580   52       1              0.8               0.2                   245   
581   31       1              1.3               0.5                   184   
582   38       1              1.0               0.3                   216   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                          16                          18             6.8   
1                          64                         100             7.5   
2                          60                          68             7.0   
3                          14                          20             6.8   
4                          27                          59             7.3   
..                        ...                         ...             ...   
578                        20                          34             5.9   
579                        35                          31             6.0   
580                        48                          49             6.4   
581                        29                          32             6.8   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  
0        3.3                        0.90  
1        3.2                        0.74  
2        3.3                        0.89  
3        3.4                        1.00  
4        2.4                        0.40  
..       ...                         ...  
578      1.6                        0.37  
579      3.2                        1.10  
580      3.2                        1.00  
581      3.4                        1.00  
582      4.4                        1.50  

[583 rows x 10 columns]

In [30]:
#Seperating output column(dependent) from the dataset
y = data.iloc[:,10:11]

In [31]:
y

Dataset
0          1
1          1
2          1
3          1
4          1
..       ...
578        2
579        1
580        1
581        1
582        2

[583 rows x 1 columns]

# LABEL ENCODING

In [32]:
minmax=preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(x).transform(x)

array([[0.70930233, 0.        , 0.00402145, ..., 0.5942029 , 0.52173913,
        0.24      ],
       [0.6744186 , 1.        , 0.14075067, ..., 0.69565217, 0.5       ,
        0.176     ],
       [0.6744186 , 1.        , 0.0924933 , ..., 0.62318841, 0.52173913,
        0.236     ],
       ...,
       [0.55813953, 1.        , 0.00536193, ..., 0.53623188, 0.5       ,
        0.28      ],
       [0.31395349, 1.        , 0.01206434, ..., 0.5942029 , 0.54347826,
        0.28      ],
       [0.39534884, 1.        , 0.0080429 , ..., 0.66666667, 0.76086957,
        0.48      ]])

In [50]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()

In [34]:
x['Gender']=l.fit_transform(x['Gender'])

In [51]:
x

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0     65       0              0.7               0.1                   187   
1     62       1             10.9               5.5                   699   
2     62       1              7.3               4.1                   490   
3     58       1              1.0               0.4                   182   
4     72       1              3.9               2.0                   195   
..   ...     ...              ...               ...                   ...   
578   60       1              0.5               0.1                   500   
579   40       1              0.6               0.1                    98   
580   52       1              0.8               0.2                   245   
581   31       1              1.3               0.5                   184   
582   38       1              1.0               0.3                   216   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                          16                          18             6.8   
1                          64                         100             7.5   
2                          60                          68             7.0   
3                          14                          20             6.8   
4                          27                          59             7.3   
..                        ...                         ...             ...   
578                        20                          34             5.9   
579                        35                          31             6.0   
580                        48                          49             6.4   
581                        29                          32             6.8   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  
0        3.3                        0.90  
1        3.2                        0.74  
2        3.3                        0.89  
3        3.4                        1.00  
4        2.4                        0.40  
..       ...                         ...  
578      1.6                        0.37  
579      3.2                        1.10  
580      3.2                        1.00  
581      3.4                        1.00  
582      4.4                        1.50  

[583 rows x 10 columns]

# WORKING WITH OUTLIERS

In [37]:
data.head(5)

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65       0              0.7               0.1                   187   
1   62       1             10.9               5.5                   699   
2   62       1              7.3               4.1                   490   
3   58       1              1.0               0.4                   182   
4   72       1              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  Dataset  
0      3.3                        0.90        1  
1      3.2                        0.74        1  
2      3.3                        0.89        1  
3      3.4                        1.00        1  
4      2.4                        0.40        1

# PERFORMING Z_SCORE

In [39]:
#Get Z-scores of data
from scipy import stats
import numpy as np
z = np.abs(stats.zscore(data))
print(z)

[[1.25209764 1.76228085 0.41887783 ... 0.19896867 0.14789798 0.63359475]
 [1.06663704 0.56744644 1.22517135 ... 0.07315659 0.65069686 0.63359475]
 [1.06663704 0.56744644 0.6449187  ... 0.19896867 0.17932291 0.63359475]
 ...
 [0.44843504 0.56744644 0.4027597  ... 0.07315659 0.16635131 0.63359475]
 [0.84978917 0.56744644 0.32216906 ... 0.32478075 0.16635131 0.63359475]
 [0.41704777 0.56744644 0.37052344 ... 1.58290153 1.73759779 1.57829591]]


In [40]:
threshold = 3
print(np.where(z > 3))

(array([ 25,  26,  27,  47,  77, 115, 116, 117, 117, 118, 118, 119, 119,
       120, 120, 121, 121, 128, 135, 135, 135, 161, 166, 168, 168, 177,
       180, 181, 195, 199, 199, 199, 199, 199, 207, 207, 233, 259, 259,
       269, 311, 311, 370, 370, 419, 420, 429, 447, 447, 447, 452, 479,
       503, 504, 504, 505, 505, 509, 519, 519, 531, 531, 546, 547, 547,
       548, 559, 559, 565, 565, 572, 575, 575, 575], dtype=int64), array([5, 5, 5, 5, 4, 4, 4, 5, 6, 5, 6, 5, 6, 2, 3, 2, 3, 4, 4, 5, 6, 4,
       2, 2, 3, 4, 7, 7, 4, 2, 3, 4, 5, 6, 5, 6, 4, 2, 3, 7, 2, 3, 2, 3,
       4, 4, 4, 2, 3, 4, 4, 5, 3, 2, 3, 2, 3, 3, 2, 3, 2, 3, 3, 2, 3, 9,
       2, 3, 2, 3, 9, 2, 3, 9], dtype=int64))


In [41]:
print(z[199][3])

3.675541869467426


In [43]:
#Get clean data by removing or filtering the outliers
data = data[(z < 3).all(axis=1)]

In [45]:
data#removed outliers

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0     65       0              0.7               0.1                   187   
1     62       1             10.9               5.5                   699   
2     62       1              7.3               4.1                   490   
3     58       1              1.0               0.4                   182   
4     72       1              3.9               2.0                   195   
..   ...     ...              ...               ...                   ...   
578   60       1              0.5               0.1                   500   
579   40       1              0.6               0.1                    98   
580   52       1              0.8               0.2                   245   
581   31       1              1.3               0.5                   184   
582   38       1              1.0               0.3                   216   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                          16                          18             6.8   
1                          64                         100             7.5   
2                          60                          68             7.0   
3                          14                          20             6.8   
4                          27                          59             7.3   
..                        ...                         ...             ...   
578                        20                          34             5.9   
579                        35                          31             6.0   
580                        48                          49             6.4   
581                        29                          32             6.8   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  Dataset  
0        3.3                        0.90        1  
1        3.2                        0.74        1  
2        3.3                        0.89        1  
3        3.4                        1.00        1  
4        2.4                        0.40        1  
..       ...                         ...      ...  
578      1.6                        0.37        2  
579      3.2                        1.10        1  
580      3.2                        1.00        1  
581      3.4                        1.00        1  
582      4.4                        1.50        2  

[536 rows x 11 columns]

In [47]:
#Find outliers using IQR Score(i.e. IQR=Q3-Q1) 
Q1 = data.quantile(0.25)
Q3 = data.quantile(0.75)
IQR = Q3 - Q1
print(IQR)

Age                            25.00
Gender                          0.00
Total_Bilirubin                 1.20
Direct_Bilirubin                0.80
Alkaline_Phosphotase          115.25
Alamine_Aminotransferase       34.25
Aspartate_Aminotransferase     51.00
Total_Protiens                  1.40
Albumin                         1.20
Albumin_and_Globulin_Ratio      0.35
Dataset                         1.00
dtype: float64


In [48]:
data = data[~((data < (Q1 - 1.5 * IQR)) |(data > (Q3 + 1.5 * IQR))).any(axis=1)]

In [49]:
data

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
3     58       1              1.0               0.4                   182   
5     46       1              1.8               0.7                   208   
8     17       1              0.9               0.3                   202   
9     55       1              0.7               0.2                   290   
10    57       1              0.6               0.1                   210   
..   ...     ...              ...               ...                   ...   
571   90       1              1.1               0.3                   215   
579   40       1              0.6               0.1                    98   
580   52       1              0.8               0.2                   245   
581   31       1              1.3               0.5                   184   
582   38       1              1.0               0.3                   216   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
3                          14                          20             6.8   
5                          19                          14             7.6   
8                          22                          19             7.4   
9                          53                          58             6.8   
10                         51                          59             5.9   
..                        ...                         ...             ...   
571                        46                         134             6.9   
579                        35                          31             6.0   
580                        48                          49             6.4   
581                        29                          32             6.8   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  Dataset  
3        3.4                         1.0        1  
5        4.4                         1.3        1  
8        4.1                         1.2        2  
9        3.4                         1.0        1  
10       2.7                         0.8        1  
..       ...                         ...      ...  
571      3.0                         0.7        1  
579      3.2                         1.1        1  
580      3.2                         1.0        1  
581      3.4                         1.0        1  
582      4.4                         1.5        2  

[270 rows x 11 columns]

In [46]:
data.shape

(536, 11)